header:
  phone: "+41 79 930 37 96"
  email: "career@mgmt.corbet.ch"
  location: "ZH, CH"

social:
  calendar: "https://connect.corbet.ch/time"
  signal: "https://signal.me/#p/+41799303796"
  whatsapp: "https://wa.me/+41799303796"
  telegram: "https://t.me/rich_co"
  linkedin: "https://www.linkedin.com/in/julian-corbet/"
  threema: "https://threema.id/7C59AZ8P"
  x: "https://x.com/USER"
  matrix: "@richc:corbet.ch"