downloads:
  - title: "CV (Onepager)"
    description: "For skimming the bare essentials"
    button: "Download CV"
    filename: "downloads/Corbet_CV_Onepager.pdf"
    
  - title: "CV (Twopager)"
    description: "To understand what I am about" 
    button: "Download CV"
    filename: "downloads/Corbet_CV_Twopager.pdf"

  - title: "Academic Excellence"
    description: "Multiple degrees | summa cum laude" 
    button: "Download Academics"
    filename: "downloads/Corbet_Education.pdf"
    
  - title: "Work References"
    description: "AI | Consulting | Corporate Finance" 
    button: "Download References"
    filename: "downloads/Corbet_References.pdf" 

  - title: "Education"
    type: "folder"
    description: "References concerning my education"
    children:
      - title: "Master of Science Physics"
        description: "AI | Data Science | ML (summa cum laude)"
        button: "Download PDF"
        filename: "downloads/education/Corbet_MSc_Physics.pdf" 
      - title: "Bachelor of Science Physics"
        description: "Biophysics | Quantum | Statistical Mechanics"
        button: "Download PDF"
        filename: "downloads/education/Corbet_BSc_Physics.pdf"
      - title: "Bachelor of Science Psychology"
        description: "AR | Neuro | Organizational Psychology | VR"
        button: "Download PDF"
        filename: "downloads/education/Corbet_BSc_Psychology.pdf"

  - title: "References"
    type: "folder"
    description: "References concerning past jobs"
    children:
      - title: "Airbus Defense & Space"
        description: "AI | Data Science | Defense | ML"
        button: "Download PDF"
        filename: "downloads/references/Corbet_Airbus.pdf" 
      - title: "Covendit Corporate Finance"
        description: "Corporate Finance | M&A | Valuation"
        button: "Download PDF"
        filename: "downloads/references/Corbet_Covendit.pdf" 
      - title: "NEXGEN Management Consulting"
        description: "Consulting | FinTech | RegTech"
        button: "Download PDF"
        filename: "downloads/references/Corbet_NEXGEN.pdf"