downloads:
  - title: "One Page CV"
    description: "View my concise CV"
    button: "Download PDF"
    filename: "downloads/Corbet_CV_Onepager.pdf"
    
  - title: "CV"
    description: "Download my CV for a detailed overview of my professional background, skills, and experience" 
    button: "Download PDF"
    filename: "downloads/Corbet_CV_Twopager.pdf"
    
  - title: "References"
    description: "Download my professional references" 
    button: "Download PDF"
    filename: "downloads/Corbet_references.pdf" 
    
  - title: "Education"
    description: "Download my education summary for an overview of my studies and degrees" 
    button: "Download PDF"
    filename: "downloads/Corbet_education.pdf"

  - title: "References"
    type: "folder"
    description: "View my references for verified documentation of my professional achievements and past roles"
    children:
      - title: "Employment reference NexGen"
        description: "Employment reference from NexGen (Focus on FinTech & Regulation of securities & Cloud) in Germany"
        button: "Download PDF"
        filename: "downloads/nexgen.pdf"
      - title: "Employment reference Airbus"
        description: "Employment reference from Airbus (Focus on defense and machine learning) in Germany"
        button: "Download PDF"
        filename: "downloads/airbus.pdf" 
      - title: "Employment reference Covendit"
        description: "Employment reference from Covendit (Focus on Corporate Finance) in Germany"
        button: "Download PDF"
        filename: "downloads/covendit.pdf" 
        
  - title: "Education"
    type: "folder"
    description: "View my academic background for a detailed overview of my studies, degrees, and research focus"
    children:
      - title: "Master Certificate Physics"
        description: "Master of Science Certificate in Physics"
        button: "Download PDF"
        filename: "downloads/msc_physics.pdf" 
      - title: "Bachelor Certificate in Psychology"
        description: "Bachelor of Science Certificate in Psychology"
        button: "Download PDF"
        filename: "downloads/education/bsc_psychology.pdf"
      - title: "Bachelor Certificate in Physics"
        description: "Bachelor of Science Certificate in Physics"
        button: "Download PDF"
        filename: "downloads/education/bsc_physics.pdf"